import React, { createContext, useContext, useState, useEffect } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';

const LANGUAGE_KEY = '@language_preference';

export const LanguageType = {
  AZERBAIJANI: 'az',
  ENGLISH: 'en',
  RUSSIAN: 'ru'
};

const DEFAULT_LANGUAGE = LanguageType.AZERBAIJANI;

const LanguageContext = createContext({
  language: DEFAULT_LANGUAGE,
  setLanguage: () => {},
  isAzerbaijani: true,
  isEnglish: false,
  isRussian: false
});

export const LanguageProvider = ({ children }) => {
  const [language, setLanguageState] = useState(DEFAULT_LANGUAGE);
  const [isLoading, setIsLoading] = useState(true);
  
  useEffect(() => {
    const loadLanguagePreference = async () => {
      try {
        const savedLanguage = await AsyncStorage.getItem(LANGUAGE_KEY);
        if (savedLanguage !== null) {
          setLanguageState(savedLanguage);
        }
      } catch (error) {
        console.error('Dil tercihi yüklenirken hata:', error);
      } finally {
        setIsLoading(false);
      }
    };

    loadLanguagePreference();
  }, []);

  const setLanguage = async (newLanguage) => {
    try {
      setLanguageState(newLanguage);
      
      await AsyncStorage.setItem(LANGUAGE_KEY, newLanguage);
    } catch (error) {
      console.error('Dil tercihi kaydedilirken hata:', error);
    }
  };

  return (
    <LanguageContext.Provider 
      value={{
        language,
        setLanguage,
        isAzerbaijani: language === LanguageType.AZERBAIJANI,
        isEnglish: language === LanguageType.ENGLISH,
        isRussian: language === LanguageType.RUSSIAN,
        isLoading,
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);

export const translations = {
  [LanguageType.AZERBAIJANI]: {
    profile: {
      title: 'Profil',
      myEvents: 'Tədbirlərim',
      myTickets: 'Biletlərim', 
      profileInfo: 'Profil Məlumatları',
      passwordChange: 'Şifrə Dəyişdirmə',
      notifications: 'Bildirişlər',
      theme: 'Tema',
      language: 'Dil',
      contact: 'Əlaqə',
      logout: 'Hesabdan çıxış',
      close: 'Bağla',
      save: 'Yadda saxla',
      cancel: 'Ləğv et',
      fullName: 'Ad Soyad',
      email: 'Email',
      phone: 'Telefon',
      currentPassword: 'Cari şifrə',
      newPassword: 'Yeni şifrə',
      confirmPassword: 'Şifrəni təsdiqlə',
      contactUs: 'Bizimlə əlaqə',
      yourMessage: 'Mesajınız',
      send: 'Göndər',
      messageSent: 'Mesajınız göndərildi!',
      successTitle: 'Uğurlu',
      profileUpdated: 'Profil məlumatları uğurla yeniləndi',
      passwordUpdated: 'Şifrəniz uğurla yeniləndi',
      code: 'kod',
      logoutConfirmTitle: 'Hesabdan çıxış',
      logoutConfirmMessage: 'Hesabdan çıxış etmək istədiyinizə əminsiniz?',
    },
    theme: {
      title: 'Tema Seçimi',
      light: 'İşıqlı rejim',
      dark: 'Qaranlıq rejim',
      system: 'Sistem ayarları'
    },
    language: {
      title: 'Dil Seçimi',
      azerbaijani: 'Azərbaycan dili',
      english: 'İngilis dili',
      russian: 'Rus dili'
    },
    notifications: {
      title: 'Bildiriş Ayarları',
      allNotifications: 'Bütün bildirişlər',
      eventReminders: 'Tədbir xatırlatmaları',
      newEvents: 'Yeni tədbirlər',
      followedOrganisers: 'İzlədiyim təşkilatçılar',
      promotions: 'Kampaniyalar və endirimlər',
      enabled: 'Aktiv',
      disabled: 'Deaktiv',
      permissionRequired: 'Bildiriş icazəsi tələb olunur',
      permissionDenied: 'Bildiriş icazəsi rədd edildi. Ayarlardan aktiv edə bilərsiniz.',
      settingsSaved: 'Bildiriş ayarları yadda saxlanıldı'
    },
    tabs: {
      home: "Ana səhifə",
      organisers: "Təşkilatçılar",
      follows: "İzləmələr",
      documents: "Sənədlər",
      profile: "Profil",
      more: "Digər"
    },
    registerModal: {
      title: "Tədbir qeydiyyatı",
      waitingListTitle: "Gözləmə siyahısına qeydiyyat",
      fullName: "Adınız və Soyadınız",
      email: "E-poçt ünvanınız",
      phone: "Telefon nömrəniz",
      finCode: "FIN Kodunuz",
      age: "Yaşınız",
      education: "Təhsil səviyyəniz",
      selectEducation: "Təhsil səviyyənizi seçin",
      work: "İş yeriniz",
      workOptional: "(istəyə bağlı)",
      acceptTerms: "qəbul edirəm",
      registrationTerms: "Qeydiyyat şərtlərini",
      participationTerms: "İştirak şərtlərini",
      loading: "Yüklənir...",
      register: "Qeydiyyatdan keç",
      participate: "İştirak et",
      waitingListNote: "Bu tədbirə qeydiyyat dolub. Gözləmə siyahısına yazılsanız, yer açıldığı təqdirdə sizə xəbər veriləcək.",
      profileNote: "Məlumatları dəyişmək üçün profilim bölümünə daxil ola bilərsiniz",
      successTitle: "Uğurlu",
      registerSuccess: "Qeydiyyat uğurla tamamlandı",
      participateSuccess: "İştirakınız təsdiqləndi",
      goToMyEvents: "Tədbirlərim bölümünə keçid",
      enterPhone: "+994XXXXXXXXX",
      enterFinCode: "FIN kodunuzu daxil edin",
      enterAge: "Yaşınızı daxil edin",
      enterWorkplace: "İş yerinizi daxil edin",
      error: {
        requiredLogin: "Qeydiyyatdan keçmək üçün daxil olmalısınız",
        acceptTerms: "Zəhmət olmasa qeydiyyat şərtlərini qəbul edin",
        acceptParticipationTerms: "Zəhmət olmasa iştirak şərtlərini qəbul edin",
        invalidName: "Ad və soyad dοğru daxil edilməlidir",
        invalidPhone: "Telefon nömrəsi düzgün formatda deyil",
        invalidFinCode: "Fin kodu 7 simvoldan ibarət olmalıdır",
        fillAllFields: "Bütün məlumatları doldurun",
        registrationError: "Qeydiyyat zamanı xəta baş verdi"
      }
    },
    filters: {
      title: 'Filtrlər',
      reset: 'Sıfırla',
      apply: 'Tətbiq et',
      dateFilter: 'Tarix filtri',
      nearFirst: 'Öncə yaxın',
      farFirst: 'Öncə uzaq',
      byDate: 'Tarix üzrə',
      region: 'Bölgə',
      eventType: 'Tədbir növü',
      paymentType: 'Ödəniş növü',
      documentType: 'Sənəd növü',
    },
    events: {
      title: 'Tədbir',
      upcoming: 'Yaxın Tədbirlər',
      featured: 'Özəl tədbirlər',
      popular: 'Populyar',
      all: 'Bütün tədbirlər',
      search: 'Tədbir axtar...',
      date: 'Tarix',
      time: 'Saat',
      location: 'Məkan',
      price: 'Qiymət',
      buyTicket: 'Bilet al',
      free: 'Pulsuz',
      starting: 'Başlangıc',
      noResults: 'Tədbir tapılmadı',
      untitledEvent: 'İsimsiz Tədbir',
      onlineEvent: 'Onlayn tədbir',
      unknown: 'Bilinmir',
      registeredEvents: 'Qeydiyyatlı Tədbirlər',
      successfulEvents: 'Uğurlu Tədbirlər',
      noEventsFound: 'Axtarışınıza uyğun tədbir tapılmadı',
      noRegisteredEvents: 'Qeydiyyatdan keçdiyiniz tədbir yoxdur',
      noSuccessfulEvents: 'Uğurla iştirak etdiyiniz tədbir yoxdur',
      cancel: 'Ləğv et',
      cancelTitle: 'Qeydiyyat ləğvi',
      cancelConfirmation: 'Bu tədbirdəki qeydiyyatınızı ləğv etmək istədiyinizə əminsiniz?',
      cancelSuccess: 'Tədbir qeydiyyatınız uğurla ləğv edildi',
      cancelError: 'Tədbir ləğv edilərkən xəta baş verdi',
      documentless: 'Sənədsiz',
      documentlessInfo: 'Bu tədbir üçün sənəd əldə etmək mümkün deyil',
      document: 'Sənəd',
      documentAvailable: 'Təşkilatçı sənədinizi əlavə edibsə, buradan görə bilərsiniz',
      documentNotAvailable: 'Bu tədbirdə hər hansı sənəd təqdim olunmur',
      viewDocument: 'Bax',
      giveFeedback: 'Rəy bildir',
      feedbackGiven: 'Rəy verildi',
      send: 'Göndər',
      close: 'Bağla',
      feedbackTitle: 'Tədbir haqqında fikirlərinizi və iradlarınızı təşkilatçı ilə buradan bölüşə bilərsiniz',
      feedbackSuccess: 'Rəyiniz uğurla göndərildi',
      feedbackError: 'Rəyiniz göndərilərkən xəta baş verdi',
      shareError: 'Tədbir paylaşıla bilmədi',
      shareTitle: 'Tədbir paylaşmaq',
      moreInfo: 'Daha ətraflı məlumat üçün',
      onlineEvent: 'Online tədbir',
      language: 'Dil',
      startDate: 'Başlama tarixi',
      endDate: 'Bitmə tarixi',
      ageRange: 'Yaş aralığı',
      years: 'yaş',
      lastRegistration: 'Son qeydiyyat',
      eventType: 'Tədbir növü',
      provideDocument: 'Veriləcək sənəd',
      paymentSystem: 'Ödəniş sistemi',
      free: 'Ödənişsiz',
      region: 'Bölgə',
      address: 'Ünvan',
      onlineEvent: 'Onlayn tədbir',
      goToLink: 'Linkə keçid et',
      dressCode: 'Geyim kodu',
      participants: 'İştirak edənlər',
      registrationCount: 'Qeydiyyat sayı',
      wantGoCount: 'Getmək istəyənlər',
      unlimited: 'Limitsiz',
      people: 'nəfər',
      eventNotFound: 'Tədbir məlumatları tapılmadı',
      eventMayDeleted: 'Axtardığınız tədbir silinmiş və ya mövcud olmaya bilər',
      goBack: 'Geri qayıt',
      linkError: 'Link açıla bilmədi',
      relatedEvents: 'Əlaqəli tədbirlər',
      unfollowError: 'İzləmə ləğv edilərkən problem yarandı',
      register: 'Qeydiyyatdan keç',
      registerRedirect: 'Qeydiyyat üçün keçid et',
      registerPhone: 'Qeydiyyat üçün',
      participate: 'İştirak et',
      accountDeactivated: 'Hesabınız deaktivdir',
      alreadyRegistered: 'Artıq qeydiyyatdan keçmisiniz',
      organizersCannotRegister: 'Təşkilatçılar qeydiyyatdan keçə bilməz',
      registrationClosed: 'Qeydiyyat bağlıdır'
    },
    tickets: {
      title: 'Biletlərim',
      active: 'Aktiv',
      expired: 'Sona çatmış',
      cancelled: 'Ləğv edilmiş',
      noTickets: 'Aktiv biletiniz yoxdur',
    },
    errors: {
      invalidCredentials: 'Yanlış e-poçt və ya şifrə',
      requiredFields: 'Bütün xanaları doldurun',
      networkError: 'Şəbəkə xətası baş verdi',
      passwordMatch: 'Şifrələr uyğun gəlmir',
      wrongPassword: 'Yanlış cari şifrə',
      invalidEmail: 'Etibarlı e-poçt ünvanı daxil edin',
      errorTitle: 'Xəta',
      permissionDenied: 'Şəkil seçmək üçün icazə lazımdır',
      imagePicking: 'Şəkil seçilərkən xəta baş verdi',
      userNotFound: 'İstifadəçi məlumatları tapılmadı. Zəhmət olmasa, yenidən daxil olun.',
      profileUpdateFailed: 'Profil məlumatları yenilənərkən xəta baş verdi',
      passwordChangeFailed: 'Şifrə dəyişdirilərkən xəta baş verdi',
      logoutFailed: 'Çıxış edərkən xəta baş verdi. Zəhmət olmasa yenidən cəhd edin.',
    },
    organisers: {
      title: 'Təşkilatçılar',
      favorite: 'Favori Təşkilatçılar',
      searchPlaceholder: 'Təşkilatçı axtar',
      organiserCount: 'təşkilatçı',
      followers: 'izləyici',
      noFavorites: 'Hələ heç bir favori təşkilatçı yoxdur.',
      noResults: 'Axtarışınıza uyğun təşkilatçı tapılmadı.',
      notFound: 'Təşkilatçı məlumatları tapılmadı',
      navigationError: 'Təşkilatçı səhifəsinə keçid edilərkən xəta yarandı',
      followedOrganisers: 'İzlədiyim təşkilatlar',
      unfollow: 'İzləmədən çıx',
      noOrganisersFollowed: 'Heç bir təşkilatı izləmirsiniz. İzlədiyiniz təşkilatların tədbirləri burada görünəcək.',
      organisation: 'Təşkilat',
      follow: 'İzlə',
      following: 'İzlənir',
      noActiveEvents: 'Aktiv tədbir tapılmadı',
      noPastEvents: 'Keçmiş tədbir tapılmadı',
      shareMessage: 'adlı təşkilatçını izləyin yeni tədbirlərdən xəbərdar olun!',
      unnamed: 'İsimsiz Organizatör',
      organiserNotFound: 'Təşkilatçı yoxdur',
      unfollowConfirm: 'Təşkilatçını izləməkdən çıxmaq istədiyinizə əminsiniz?',
      organizer: 'Təşkilatçı',
      about: 'Haqqında',
      contact: 'Əlaqə',
      phone: 'Telefon',
      showMore: 'Daha çox',
      showLess: 'Daha az',
      activeEvents: 'Aktiv tədbirlər',
      pastEvents: 'Keçmiş tədbirlər',
      unfollowError: 'İzləmə ləğv edilərkən problem yarandı'
    },
    
    general: {
      category: 'Kateqoriya',
      allCategories: 'Bütün sahələr',
      error: 'Xəta',
      cancel: 'Bağla',
      confirm: 'Təsdiqlə',
      delete: 'Sil',
      search: 'Axtar',
      success: 'Uğurlu',
      info: 'Məlumat',
      addressCopied: 'Ünvan kopyalandı',
      addressCopyError: 'Ünvan kopyalanarkən xəta baş verdi',
      calendarAppMissing: 'Təqvim tətbiqi tapılmadı',
      eventAddedToCalendar: 'Tədbir təqviminizə əlavə edildi',
      calendarError: 'Təqvimə əlavə edilərkən xəta baş verdi',
      addToCalendar: 'Təqvimə əlavə et'
    },
    
    search: {
      searchEvent: 'Tədbir axtar',
      searchOrganisation: 'Təşkilat axtar',
      searchDocument: 'Sənəd axtar'
    },
    
    documents: {
      myDocuments: "Sənədlərim",
      documentsOf: "sənədləri",
      documentDetails: "Sənəd Detalları",
      documentName: "Sənəd adı",
      certificate: "Sertifikat",
      eventType: "Tədbir növü",
      viewDetails: "Ətraflı bax",
      pdfDocument: "PDF Sənədi",
      download: "Endir",
      open: "Aç",
      confirmDeleteDocument: "Bu sənədi silmək istədiyinizə əminsiniz?",
      documentNotFound: "Seçili sənəd tapılmadı",
      documentDeletedSuccess: "Sənəd uğurla silindi",
      documentDeleteError: "Sənəd silinərkən xəta baş verdi. Xəta: ",
      addNewDocument: "Yeni Sənəd Əlavə Et",
      noDocumentsFound: "Heç bir sənəd tapılmadı",
      documentContent: "Sənəd məzmunu",
      organizerName: "Təşkilatçı adı",
      organizerWebsite: "Təşkilatçı veb-saytı",
      organizerId: "Təşkilatçı ID",
      selectEventType: "Tədbir növü seçin",
      selectDocumentType: "Sənəd növü seçin",
      startDate: "Başlama tarixi",
      endDate: "Bitmə tarixi",
      addDocument: "Sənəd əlavə et",
      documentType: "Sənəd növü",
      organizer: "Təşkilatçı",
      verifiedDocument: "Bu sənəd eventin tərəfindən təsdiq edilib",
      goToOrganizerProfile: "Təşkilatçı profilinə keçid et"
    },
  },
  
  [LanguageType.ENGLISH]: {
    profile: {
      title: 'Profile',
      myEvents: 'My Events',
      myTickets: 'My Tickets', 
      profileInfo: 'Profile Information',
      passwordChange: 'Change Password',
      notifications: 'Notifications',
      theme: 'Theme',
      language: 'Language',
      contact: 'Contact',
      logout: 'Logout',
      close: 'Close',
      save: 'Save',
      cancel: 'Cancel',
      fullName: 'Full Name',
      email: 'Email',
      phone: 'Phone',
      currentPassword: 'Current Password',
      newPassword: 'New Password',
      confirmPassword: 'Confirm Password',
      contactUs: 'Contact Us',
      yourMessage: 'Your Message',
      send: 'Send',
      messageSent: 'Your message has been sent!',
      successTitle: 'Success',
      profileUpdated: 'Profile information updated successfully',
      passwordUpdated: 'Your password has been updated successfully',
      code: 'code',
      logoutConfirmTitle: 'Logout',
      logoutConfirmMessage: 'Are you sure you want to logout?',
    },
    theme: {
      title: 'Theme Selection',
      light: 'Light Mode',
      dark: 'Dark Mode',
      system: 'System Settings'
    },
    language: {
      title: 'Language Selection',
      azerbaijani: 'Azerbaijani',
      english: 'English',
      russian: 'Russian'
    },
    notifications: {
      title: 'Notification Settings',
      allNotifications: 'All notifications',
      eventReminders: 'Event reminders',
      newEvents: 'New events',
      followedOrganisers: 'Followed organisers',
      promotions: 'Promotions and discounts',
      enabled: 'Enabled',
      disabled: 'Disabled',
      permissionRequired: 'Notification permission required',
      permissionDenied: 'Notification permission denied. You can enable it from settings.',
      settingsSaved: 'Notification settings saved'
    },
    tabs: {
      home: "Home",
      organisers: "Organisers",
      follows: "Follows",
      documents: "Documents",
      profile: "Profile",
      more: "More"
    },
    registerModal: {
      title: "Event Registration",
      waitingListTitle: "Waiting List Registration",
      fullName: "Full Name",
      email: "Email Address",
      phone: "Phone Number",
      finCode: "FIN Code",
      age: "Age",
      education: "Education Level",
      selectEducation: "Select your education level",
      work: "Workplace",
      workOptional: "(optional)",
      acceptTerms: "accept",
      registrationTerms: "Registration terms",
      participationTerms: "Participation terms",
      loading: "Loading...",
      register: "Register",
      participate: "Participate",
      waitingListNote: "Registration for this event is full. If you sign up for the waiting list, you will be notified if a spot becomes available.",
      profileNote: "You can change your information in the profile section",
      successTitle: "Success",
      registerSuccess: "Registration completed successfully",
      participateSuccess: "Your participation has been confirmed",
      goToMyEvents: "Go to My Events",
      enterPhone: "+994XXXXXXXXX",
      enterFinCode: "Enter your FIN code",
      enterAge: "Enter your age",
      enterWorkplace: "Enter your workplace",
      error: {
        requiredLogin: "You must be logged in to register",
        acceptTerms: "Please accept the registration terms",
        acceptParticipationTerms: "Please accept the participation terms",
        invalidName: "Please enter a valid full name",
        invalidPhone: "Phone number format is incorrect",
        invalidFinCode: "FIN code must be 7 characters",
        fillAllFields: "Please fill in all fields",
        registrationError: "An error occurred during registration"
      }
    },
    filters: {
      title: 'Filters',
      reset: 'Reset',
      apply: 'Apply',
      dateFilter: 'Date filter',
      nearFirst: 'Nearest first',
      farFirst: 'Farthest first',
      byDate: 'By date',
      region: 'Region',
      eventType: 'Event type',
      paymentType: 'Payment type',
      documentType: 'Document type',
    },
    events: {
      title: 'Events',
      upcoming: 'Upcoming Events',
      featured: 'Featured Events',
      popular: 'Popular',
      all: 'All Events',
      search: 'Search events...',
      date: 'Date',
      time: 'Time',
      location: 'Location',
      price: 'Price',
      buyTicket: 'Buy Ticket',
      free: 'Free',
      starting: 'Starting',
      noResults: 'No events found',
      untitledEvent: 'Untitled Event',
      onlineEvent: 'Online Event',
      unknown: 'Unknown',
      registeredEvents: 'Registered Events',
      successfulEvents: 'Successful Events',
      noEventsFound: 'No events found for your search',
      noRegisteredEvents: 'You have no registered events',
      noSuccessfulEvents: 'You have no successfully attended events',
      cancel: 'Cancel',
      cancelTitle: 'Cancel Registration',
      cancelConfirmation: 'Are you sure you want to cancel your registration for this event?',
      cancelSuccess: 'Your event registration was successfully canceled',
      cancelError: 'An error occurred while canceling the event',
      documentless: 'No Document',
      documentlessInfo: 'It is not possible to obtain a document for this event',
      document: 'Document',
      documentAvailable: 'If the organizer has added your document, you can view it here',
      documentNotAvailable: 'No document is provided for this event',
      viewDocument: 'View',
      giveFeedback: 'Give Feedback',
      feedbackGiven: 'Feedback Given',
      send: 'Send',
      close: 'Close',
      feedbackTitle: 'You can share your thoughts and objections about the event with the organizer here',
      feedbackSuccess: 'Your feedback has been successfully submitted',
      feedbackError: 'An error occurred while submitting your feedback',
      shareError: 'Event could not be shared',
      shareTitle: 'Share Event',
      moreInfo: 'For more information',
      onlineEvent: 'Online Event',
      language: 'Language',
      startDate: 'Start date',
      endDate: 'End date',
      ageRange: 'Age range',
      years: 'years',
      lastRegistration: 'Last registration',
      eventType: 'Event type',
      provideDocument: 'Document type',
      paymentSystem: 'Payment system',
      free: 'Free',
      region: 'Region',
      address: 'Address',
      onlineEvent: 'Online event',
      goToLink: 'Go to link',
      dressCode: 'Dress code',
      participants: 'Participants',
      registrationCount: 'Registration count',
      unlimited: 'Unlimited',
      people: 'people',
      eventNotFound: 'Event information not found',
      eventMayDeleted: 'The event you are looking for may have been deleted or does not exist',
      goBack: 'Go back',
      linkError: 'Link could not be opened',
      relatedEvents: 'Related events',
      unfollowError: 'A problem occurred while unfollowing',
      register: 'Register',
      registerRedirect: 'Go to registration',
      registerPhone: 'For registration',
      participate: 'Participate',
      accountDeactivated: 'Your account is deactivated',
      alreadyRegistered: 'You are already registered',
      organizersCannotRegister: 'Organizers cannot register',
      registrationClosed: 'Registration is closed',
      wantGoCount: 'Want to go'
    },
    tickets: {
      title: 'My Tickets',
      active: 'Active',
      expired: 'Expired',
      cancelled: 'Cancelled',
      noTickets: 'You have no active tickets',
    },
    errors: {
      invalidCredentials: 'Invalid email or password',
      requiredFields: 'Please fill all fields',
      networkError: 'A network error occurred',
      passwordMatch: 'Passwords do not match',
      wrongPassword: 'Wrong current password',
      invalidEmail: 'Please enter a valid email address',
      errorTitle: 'Error',
      permissionDenied: 'Permission to access gallery is required',
      imagePicking: 'Error while selecting image',
      userNotFound: 'User data not found. Please log in again.',
      profileUpdateFailed: 'Error updating profile information',
      passwordChangeFailed: 'Error changing password',
      logoutFailed: 'Error during logout. Please try again.',
    },
    organisers: {
      title: 'Organizers',
      favorite: 'Favorite Organizers',
      searchPlaceholder: 'Search organizer',
      organiserCount: 'organizers',
      followers: 'followers',
      noFavorites: 'You don\'t have any favorite organizers yet.',
      noResults: 'No organizers found for your search.',
      notFound: 'Organizer information not found',
      navigationError: 'Error occurred when navigating to organizer page',
      followedOrganisers: 'Organizations I Follow',
      unfollow: 'Unfollow',
      noOrganisersFollowed: 'You are not following any organizations. Events from organizations you follow will appear here.',
      organisation: 'Organization',
      follow: 'Follow',
      following: 'Following',
      noActiveEvents: 'No active events found',
      noPastEvents: 'No past events found',
      shareMessage: 'Follow this organizer to get updates about new events!',
      unnamed: 'Unnamed Organizer',
      organiserNotFound: 'Organizer not found',
      unfollowConfirm: 'Are you sure you want to unfollow this organizer?',
      organizer: 'Organizer',
      about: 'About',
      contact: 'Contact',
      phone: 'Phone',
      showMore: 'Show more',
      showLess: 'Show less',
      activeEvents: 'Active events',
      pastEvents: 'Past events',
      unfollowError: 'A problem occurred while unfollowing'
    },
    
    general: {
      category: 'Category',
      allCategories: 'All Fields',
      error: 'Error',
      cancel: 'Close',
      confirm: 'Confirm',
      delete: 'Delete',
      search: 'Search',
      success: 'Success',
      info: 'Information',
      addressCopied: 'Address copied',
      addressCopyError: 'Error occurred while copying address',
      calendarAppMissing: 'Calendar application not found',
      eventAddedToCalendar: 'Event added to your calendar',
      calendarError: 'Error occurred while adding to calendar',
      addToCalendar: 'Add to calendar'
    },
    
    search: {
      searchEvent: 'Search event',
      searchOrganisation: 'Search organization',
      searchDocument: 'Search document'
    },
    
    documents: {
      myDocuments: "My Documents",
      documentsOf: "documents",
      documentDetails: "Document Details",
      documentName: "Document Name",
      certificate: "Certificate",
      eventType: "Event Type",
      viewDetails: "View Details",
      pdfDocument: "PDF Document",
      download: "Download",
      open: "Open",
      confirmDeleteDocument: "Are you sure you want to delete this document?",
      documentNotFound: "Selected document not found",
      documentDeletedSuccess: "Document successfully deleted",
      documentDeleteError: "Error occurred while deleting document. Error: ",
      addNewDocument: "Add New Document",
      noDocumentsFound: "No documents found",
      documentContent: "Document content",
      organizerName: "Organizer name",
      organizerWebsite: "Organizer website",
      organizerId: "Organizer ID",
      selectEventType: "Select event type",
      selectDocumentType: "Select document type",
      startDate: "Start date",
      endDate: "End date",
      addDocument: "Add document",
      documentType: "Document type",
      organizer: "Organizer",
      verifiedDocument: "This document is verified by eventin",
      goToOrganizerProfile: "Go to organizer profile"
    },
  },
  
  [LanguageType.RUSSIAN]: {
    profile: {
      title: 'Профиль',
      myEvents: 'Мои мероприятия',
      myTickets: 'Мои билеты', 
      profileInfo: 'Информация профиля',
      passwordChange: 'Изменить пароль',
      notifications: 'Уведомления',
      theme: 'Тема',
      language: 'Язык',
      contact: 'Контакт',
      logout: 'Выйти',
      close: 'Закрыть',
      save: 'Сохранить',
      cancel: 'Отмена',
      fullName: 'Полное имя',
      email: 'Эл. почта',
      phone: 'Телефон',
      currentPassword: 'Текущий пароль',
      newPassword: 'Новый пароль',
      confirmPassword: 'Подтвердите пароль',
      contactUs: 'Свяжитесь с нами',
      yourMessage: 'Ваше сообщение',
      send: 'Отправить',
      messageSent: 'Ваше сообщение отправлено!',
      successTitle: 'Успех',
      profileUpdated: 'Информация профиля успешно обновлена',
      passwordUpdated: 'Ваш пароль успешно обновлен',
      code: 'код',
      logoutConfirmTitle: 'Выход из аккаунта',
      logoutConfirmMessage: 'Вы уверены, что хотите выйти из аккаунта?',
    },
    theme: {
      title: 'Выбор темы',
      light: 'Светлый режим',
      dark: 'Темный режим',
      system: 'Системные настройки'
    },
    language: {
      title: 'Выбор языка',
      azerbaijani: 'Азербайджанский',
      english: 'Английский',
      russian: 'Русский'
    },
    notifications: {
      title: 'Настройки уведомлений',
      allNotifications: 'Все уведомления',
      eventReminders: 'Напоминания о мероприятиях',
      newEvents: 'Новые мероприятия',
      followedOrganisers: 'Отслеживаемые организаторы',
      promotions: 'Акции и скидки',
      enabled: 'Включено',
      disabled: 'Отключено',
      permissionRequired: 'Требуется разрешение на уведомления',
      permissionDenied: 'Разрешение на уведомления отклонено. Вы можете включить его в настройках.',
      settingsSaved: 'Настройки уведомлений сохранены'
    },
    tabs: {
      home: "Главная",
      organisers: "Организаторы",
      follows: "Подписки",
      documents: "Документы",
      profile: "Профиль",
      more: "Ещё"
    },
    registerModal: {
      title: "Регистрация на мероприятие",
      waitingListTitle: "Регистрация в лист ожидания",
      fullName: "Имя и фамилия",
      email: "Адрес электронной почты",
      phone: "Номер телефона",
      finCode: "FIN-код",
      age: "Возраст",
      education: "Уровень образования",
      selectEducation: "Выберите ваш уровень образования",
      work: "Место работы",
      workOptional: "(необязательно)",
      acceptTerms: "принимаю",
      registrationTerms: "Условия регистрации",
      participationTerms: "Условия участия",
      loading: "Загрузка...",
      register: "Зарегистрироваться",
      participate: "Участвовать",
      waitingListNote: "Регистрация на это мероприятие заполнена. Если вы запишетесь в лист ожидания, вам сообщат, если освободится место.",
      profileNote: "Вы можете изменить свои данные в разделе профиля",
      successTitle: "Успех",
      registerSuccess: "Регистрация успешно завершена",
      participateSuccess: "Ваше участие подтверждено",
      goToMyEvents: "Перейти к моим мероприятиям",
      enterPhone: "+994XXXXXXXXX",
      enterFinCode: "Введите ваш FIN-код",
      enterAge: "Введите ваш возраст",
      enterWorkplace: "Введите ваше место работы",
      error: {
        requiredLogin: "Для регистрации необходимо войти в систему",
        acceptTerms: "Пожалуйста, примите условия регистрации",
        acceptParticipationTerms: "Пожалуйста, примите условия участия",
        invalidName: "Пожалуйста, введите корректное имя и фамилию",
        invalidPhone: "Неверный формат номера телефона",
        invalidFinCode: "FIN-код должен содержать 7 символов",
        fillAllFields: "Пожалуйста, заполните все поля",
        registrationError: "Произошла ошибка во время регистрации"
      }
    },
    filters: {
      title: 'Фильтры',
      reset: 'Сбросить',
      apply: 'Применить',
      dateFilter: 'Фильтр даты',
      nearFirst: 'Сначала ближайшие',
      farFirst: 'Сначала дальние',
      byDate: 'По дате',
      region: 'Регион',
      eventType: 'Тип мероприятия',
      paymentType: 'Тип оплаты',
      documentType: 'Тип документа',
    },
    events: {
      title: 'События',
      upcoming: 'Предстоящие события',
      featured: 'Особые события',
      popular: 'Популярные',
      all: 'Все события',
      search: 'Поиск событий...',
      date: 'Дата',
      time: 'Время',
      location: 'Место',
      price: 'Цена',
      buyTicket: 'Купить билет',
      free: 'Бесплатно',
      starting: 'Начало',
      noResults: 'События не найдены',
      untitledEvent: 'Безымянное событие',
      onlineEvent: 'Онлайн событие',
      unknown: 'Неизвестно',
      registeredEvents: 'Зарегистрированные события',
      successfulEvents: 'Успешные события',
      noEventsFound: 'По вашему запросу ничего не найдено',
      noRegisteredEvents: 'У вас нет зарегистрированных событий',
      noSuccessfulEvents: 'У вас нет успешно посещенных событий',
      cancel: 'Отменить',
      cancelTitle: 'Отменить регистрацию',
      cancelConfirmation: 'Вы уверены, что хотите отменить регистрацию на это мероприятие?',
      cancelSuccess: 'Ваша регистрация на мероприятие успешно отменена',
      cancelError: 'Произошла ошибка при отмене мероприятия',
      documentless: 'Без документа',
      documentlessInfo: 'Невозможно получить документ для этого мероприятия',
      document: 'Документ',
      documentAvailable: 'Если организатор добавил ваш документ, вы можете просмотреть его здесь',
      documentNotAvailable: 'Для этого мероприятия не предоставляется документ',
      viewDocument: 'Просмотр',
      giveFeedback: 'Оставить отзыв',
      feedbackGiven: 'Отзыв оставлен',
      send: 'Отправить',
      close: 'Закрыть',
      feedbackTitle: 'Вы можете поделиться своими мыслями и возражениями о мероприятии с организатором здесь',
      feedbackSuccess: 'Ваш отзыв успешно отправлен',
      feedbackError: 'Произошла ошибка при отправке вашего отзыва',
      shareError: 'Не удалось поделиться событием',
      shareTitle: 'Поделиться событием',
      moreInfo: 'Для получения дополнительной информации',
      onlineEvent: 'Онлайн мероприятие',
      language: 'Язык',
      startDate: 'Дата начала',
      endDate: 'Дата окончания',
      ageRange: 'Возрастной диапазон',
      years: 'лет',
      lastRegistration: 'Последняя регистрация',
      eventType: 'Тип мероприятия',
      provideDocument: 'Предоставляемый документ',
      paymentSystem: 'Система оплаты',
      free: 'Бесплатно',
      region: 'Регион',
      address: 'Адрес',
      onlineEvent: 'Онлайн мероприятие',
      goToLink: 'Перейти по ссылке',
      dressCode: 'Дресс-код',
      participants: 'Участники',
      registrationCount: 'Количество регистраций',
      unlimited: 'Без ограничений',
      people: 'человек',
      eventNotFound: 'Информация о мероприятии не найдена',
      eventMayDeleted: 'Искомое вами мероприятие могло быть удалено или не существует',
      goBack: 'Вернуться назад',
      linkError: 'Не удалось открыть ссылку',
      relatedEvents: 'Похожие мероприятия',
      unfollowError: 'Возникла проблема при отписке',
      register: 'Зарегистрироваться',
      registerRedirect: 'Перейти к регистрации',
      registerPhone: 'Для регистрации',
      participate: 'Участвовать',
      accountDeactivated: 'Ваш аккаунт деактивирован',
      alreadyRegistered: 'Вы уже зарегистрированы',
      organizersCannotRegister: 'Организаторы не могут регистрироваться',
      registrationClosed: 'Регистрация закрыта',
      wantGoCount: 'Хотят пойти'
    },
    tickets: {
      title: 'Мои билеты',
      active: 'Активные',
      expired: 'Истекшие',
      cancelled: 'Отмененные',
      noTickets: 'У вас нет активных билетов',
    },
    errors: {
      invalidCredentials: 'Неверный email или пароль',
      requiredFields: 'Пожалуйста, заполните все поля',
      networkError: 'Произошла сетевая ошибка',
      passwordMatch: 'Пароли не совпадают',
      wrongPassword: 'Неверный текущий пароль',
      invalidEmail: 'Пожалуйста, введите действительный адрес электронной почты',
      errorTitle: 'Ошибка',
      permissionDenied: 'Необходимо разрешение для выбора изображения',
      imagePicking: 'Произошла ошибка при выборе изображения',
      userNotFound: 'Информация о пользователе не найдена. Пожалуйста, войдите снова.',
      profileUpdateFailed: 'Произошла ошибка при обновлении информации профиля',
      passwordChangeFailed: 'Произошла ошибка при изменении пароля',
      logoutFailed: 'Произошла ошибка при выходе из системы. Пожалуйста, попробуйте еще раз.',
    },
    organisers: {
      title: 'Организаторы',
      favorite: 'Избранные организаторы',
      searchPlaceholder: 'Поиск организатора',
      organiserCount: 'организаторов',
      followers: 'подписчиков',
      noFavorites: 'У вас пока нет избранных организаторов.',
      noResults: 'По вашему запросу не найдено организаторов.',
      notFound: 'Информация об организаторе не найдена',
      navigationError: 'Произошла ошибка при переходе на страницу организатора',
      followedOrganisers: 'Организации, на которые я подписан',
      unfollow: 'Отписаться',
      noOrganisersFollowed: 'Вы не подписаны ни на одну организацию. Здесь будут отображаться мероприятия от организаций, на которые вы подписаны.',
      organisation: 'Организация',
      follow: 'Подписаться',
      following: 'Подписан',
      noActiveEvents: 'Активных мероприятий не найдено',
      noPastEvents: 'Прошедших мероприятий не найдено',
      shareMessage: 'Подпишитесь на этого организатора, чтобы узнавать о новых мероприятиях!',
      unnamed: 'Безымянный организатор',
      organiserNotFound: 'Организатор не найден',
      unfollowConfirm: 'Вы уверены, что хотите отписаться от этого организатора?',
      organizer: 'Организатор',
      about: 'О нас',
      contact: 'Контакт',
      phone: 'Телефон',
      showMore: 'Показать больше',
      showLess: 'Показать меньше',
      activeEvents: 'Активные мероприятия',
      pastEvents: 'Прошедшие мероприятия',
      unfollowError: 'Возникла проблема при отписке'
    },
    
    general: {
      category: 'Категория',
      allCategories: 'Все области',
      error: 'Ошибка',
      cancel: 'Закрыть',
      confirm: 'Подтвердить',
      delete: 'Удалить',
      search: 'Поиск',
      success: 'Успех',
      info: 'Информация',
      addressCopied: 'Адрес скопирован',
      addressCopyError: 'Произошла ошибка при копировании адреса',
      calendarAppMissing: 'Приложение календаря не найдено',
      eventAddedToCalendar: 'Событие добавлено в ваш календарь',
      calendarError: 'Произошла ошибка при добавлении в календарь',
      addToCalendar: 'Добавить в календарь'
    },
    
    search: {
      searchEvent: 'Поиск мероприятия',
      searchOrganisation: 'Поиск организации',
      searchDocument: 'Поиск документа'
    },
    
    documents: {
      myDocuments: "Мои документы",
      documentsOf: "документы",
      documentDetails: "Детали документа",
      documentName: "Название документа",
      certificate: "Сертификат",
      eventType: "Тип мероприятия",
      viewDetails: "Посмотреть детали",
      pdfDocument: "PDF документ",
      download: "Скачать",
      open: "Открыть",
      confirmDeleteDocument: "Вы уверены, что хотите удалить этот документ?",
      documentNotFound: "Выбранный документ не найден",
      documentDeletedSuccess: "Документ успешно удален",
      documentDeleteError: "Произошла ошибка при удалении документа. Ошибка: ",
      addNewDocument: "Добавить новый документ",
      noDocumentsFound: "Документы не найдены",
      documentContent: "Содержание документа",
      organizerName: "Имя организатора",
      organizerWebsite: "Сайт организатора",
      organizerId: "ID организатора",
      selectEventType: "Выберите тип мероприятия",
      selectDocumentType: "Выберите тип документа",
      startDate: "Дата начала",
      endDate: "Дата окончания",
      addDocument: "Добавить документ",
      documentType: "Тип документа",
      organizer: "Организатор",
      verifiedDocument: "Этот документ подтвержден eventin",
      goToOrganizerProfile: "Перейти к профилю организатора"
    },
  },
}; 